package com.financio.core.backup

import kotlinx.serialization.Serializable

/**
 * Categories and rules are exported by *name*, not by their local numeric id: that id is a
 * Room-autogenerated row id that means nothing on a different install (or even the same install
 * after a reinstall). A rule references its category by [RuleExport.categoryName] for the same
 * reason [com.financio.core.categorize.DefaultCategorization]'s seed data does.
 */
@Serializable
data class CategoryExport(val name: String, val colorHex: String)

@Serializable
data class RuleExport(
    val categoryName: String,
    /** [com.financio.core.model.MatchType] name, kept as a plain string so this format has no Kotlin-enum coupling. */
    val matchType: String,
    val pattern: String,
    val priority: Int,
)

/**
 * The on-disk shape for "alles" or "losse onderdelen": either list may be empty (or absent in
 * the JSON, via [BackupSerializer]'s default values) so the same format covers a categories-only
 * export, a rules-only export, and a combined one without three different file shapes.
 */
@Serializable
data class BackupBundle(
    val categories: List<CategoryExport> = emptyList(),
    val rules: List<RuleExport> = emptyList(),
)
